sudo: false
language: python
python:
    - "3.6"
    - "3.7"
install: 
    - pip install -r requirements.txt
    - pip install pytest
script: 
    - pytest .
after_success: 
    - echo "ALL TESTS PASSED"
deploy:
  provider: pypi
  user: 
    secure: "Pypi username"
  password:
    secure: "Pypi password"